### ISSUE TITLE
Missing game schedules on Safari

### ISSUE THREAD

**Issue by saulxy** [cguZZman/quiniela-extjs#1]
![f039c5b9-8e4a-4408-b811-75d777ab261e](https://user-images.githubusercontent.com/6466643/41540954-464c0cde-72df-11e8-8a62-abd13db4ba1d.jpg | width=100)

Safari on iOS is not loading the game schedules.

**Comment by cguZZman** [comment]
Fixed with 875ce56fb74d7c06d9b1bd1fc8898e005c6164e8
